services:

  ecommerce2:
    build:
     context: ./ecommerce2
     dockerfile: Dockerfile
    ports:
      - "7069:8081"
    depends_on:
      - rabbitmq
      - sqlserver

  inventory-api:
    build:
      context: ./InventoryAPI
      dockerfile: Dockerfile
    ports:
      - "7070:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
